//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollectionsAndGenerics.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CollectionsAndGenerics.Constants.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Task 1\n2. Task 2\n3. Task 3\n4. Task 4\n6. Task 6\n7. Exit.
        /// </summary>
        public static string AvailabletasksPrompt {
            get {
                return ResourceManager.GetString("AvailabletasksPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book titles in the {0} : .
        /// </summary>
        public static string BookTitlesInTheList {
            get {
                return ResourceManager.GetString("BookTitlesInTheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collections and Generics.
        /// </summary>
        public static string ColllectionsAndGenrericsTitle {
            get {
                return ResourceManager.GetString("ColllectionsAndGenrericsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do {0} exists in the {1} : {2}.
        /// </summary>
        public static string DoItemExistInList {
            get {
                return ResourceManager.GetString("DoItemExistInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a string to reverse : .
        /// </summary>
        public static string EnterStringToReverse {
            get {
                return ResourceManager.GetString("EnterStringToReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter which task to run : .
        /// </summary>
        public static string EnterTask {
            get {
                return ResourceManager.GetString("EnterTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid input !.
        /// </summary>
        public static string EnterValidInput {
            get {
                return ResourceManager.GetString("EnterValidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input cannot be empty !.
        /// </summary>
        public static string InputCannotBeEmpty {
            get {
                return ResourceManager.GetString("InputCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key : {0}, Value : {1}.
        /// </summary>
        public static string KeyAndValue {
            get {
                return ResourceManager.GetString("KeyAndValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name : {0}, Grade : {1}.
        /// </summary>
        public static string NameGrade {
            get {
                return ResourceManager.GetString("NameGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peoples in the {0}.
        /// </summary>
        public static string PeoplesInQueue {
            get {
                return ResourceManager.GetString("PeoplesInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nPress enter to exit task {0}.
        /// </summary>
        public static string PressEnterToExitTask {
            get {
                return ResourceManager.GetString("PressEnterToExitTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reversed string of {0} is : {1}.
        /// </summary>
        public static string ReversedStringOfSampleString {
            get {
                return ResourceManager.GetString("ReversedStringOfSampleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of integer array : {0}.
        /// </summary>
        public static string SumOfIntegerArray {
            get {
                return ResourceManager.GetString("SumOfIntegerArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of integer list : {0}.
        /// </summary>
        public static string SumOfIntegerList {
            get {
                return ResourceManager.GetString("SumOfIntegerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of integer stack : {0}.
        /// </summary>
        public static string SumOfIntegerStack {
            get {
                return ResourceManager.GetString("SumOfIntegerStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task {0}\n.
        /// </summary>
        public static string TaskTitle {
            get {
                return ResourceManager.GetString("TaskTitle", resourceCulture);
            }
        }
    }
}
