//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reflections.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reflections.Constants.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type can&apos;t be initiated, so unable to get values..
        /// </summary>
        public static string CantGetValues {
            get {
                return ResourceManager.GetString("CantGetValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for parameter {0}({1}) : .
        /// </summary>
        public static string EnterArgumentValue {
            get {
                return ResourceManager.GetString("EnterArgumentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a path of the file to inspect : .
        /// </summary>
        public static string EnterPath {
            get {
                return ResourceManager.GetString("EnterPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid index !.
        /// </summary>
        public static string EnterValidIndex {
            get {
                return ResourceManager.GetString("EnterValidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid option !.
        /// </summary>
        public static string EnterValidOption {
            get {
                return ResourceManager.GetString("EnterValidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter which task to run : .
        /// </summary>
        public static string EnterWhichTaskToRun {
            get {
                return ResourceManager.GetString("EnterWhichTaskToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception caught while invoking method : {0}.
        /// </summary>
        public static string ExceptionCaught {
            get {
                return ResourceManager.GetString("ExceptionCaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The file can&apos;t be load {0}&quot;.
        /// </summary>
        public static string FileCantLoaded {
            get {
                return ResourceManager.GetString("FileCantLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input cannot be empty !.
        /// </summary>
        public static string InputCannotEmpty {
            get {
                return ResourceManager.GetString("InputCannotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method invoke for this method is not supported !.
        /// </summary>
        public static string MethodInvokeNotSupported {
            get {
                return ResourceManager.GetString("MethodInvokeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a reserved keyword in c#.
        /// </summary>
        public static string NameIsReservedKeyword {
            get {
                return ResourceManager.GetString("NameIsReservedKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        public static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No events exists.
        /// </summary>
        public static string NoEventExists {
            get {
                return ResourceManager.GetString("NoEventExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fields exists.
        /// </summary>
        public static string NoFieldExists {
            get {
                return ResourceManager.GetString("NoFieldExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file exists in the specified path !.
        /// </summary>
        public static string NoFileExists {
            get {
                return ResourceManager.GetString("NoFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No methods exists.
        /// </summary>
        public static string NoMethodExists {
            get {
                return ResourceManager.GetString("NoMethodExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No properties exist.
        /// </summary>
        public static string NoPropertyExists {
            get {
                return ResourceManager.GetString("NoPropertyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is not a valid .NET assembly !.
        /// </summary>
        public static string NotValidAssembly {
            get {
                return ResourceManager.GetString("NotValidAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid identifier name.
        /// </summary>
        public static string NotValidIdentifierName {
            get {
                return ResourceManager.GetString("NotValidIdentifierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No types exist.
        /// </summary>
        public static string NoTypeExists {
            get {
                return ResourceManager.GetString("NoTypeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to null.
        /// </summary>
        public static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance is null.
        /// </summary>
        public static string NullInstance {
            get {
                return ResourceManager.GetString("NullInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press enter to exit.
        /// </summary>
        public static string PressEnterToExit {
            get {
                return ResourceManager.GetString("PressEnterToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter what you want to do : .
        /// </summary>
        public static string PromptUserWhatToDo {
            get {
                return ResourceManager.GetString("PromptUserWhatToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Type.
        /// </summary>
        public static string PropertyType {
            get {
                return ResourceManager.GetString("PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflection tools and tasks.
        /// </summary>
        public static string ReflectionTitle {
            get {
                return ResourceManager.GetString("ReflectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return type.
        /// </summary>
        public static string ReturnType {
            get {
                return ResourceManager.GetString("ReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type elapsed for serialization using reflection is {0}.
        /// </summary>
        public static string SerializationUsingReflection {
            get {
                return ResourceManager.GetString("SerializationUsingReflection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type elapsed for serialization using reflection and op code is {0}.
        /// </summary>
        public static string SerializationUsingReflectionEmit {
            get {
                return ResourceManager.GetString("SerializationUsingReflectionEmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract test failed.
        /// </summary>
        public static string SubTestFailed {
            get {
                return ResourceManager.GetString("SubTestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract test passed.
        /// </summary>
        public static string SubTestPassed {
            get {
                return ResourceManager.GetString("SubTestPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum test failed.
        /// </summary>
        public static string SumTestFailed {
            get {
                return ResourceManager.GetString("SumTestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum test passed.
        /// </summary>
        public static string SumTestPassed {
            get {
                return ResourceManager.GetString("SumTestPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Test add method\n2. Test subtract method\n3. Exit\n.
        /// </summary>
        public static string TestMenu {
            get {
                return ResourceManager.GetString("TestMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type can&apos;t be initiated.
        /// </summary>
        public static string TypeCantInitiated {
            get {
                return ResourceManager.GetString("TypeCantInitiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type instantiation failed.
        /// </summary>
        public static string TypeInstatiationFailed {
            get {
                return ResourceManager.GetString("TypeInstatiationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} not supported.
        /// </summary>
        public static string TypeNotSupported {
            get {
                return ResourceManager.GetString("TypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
