//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTracker.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PromptMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PromptMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpenseTracker.Constants.PromptMessages", typeof(PromptMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current balance : {0}\nTotal income : +{1}\nTotal expense : -{2}\n.
        /// </summary>
        internal static string AccountStats {
            get {
                return ResourceManager.GetString("AccountStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories : .
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n1. Amount\n2. {0}\n3. Go back\n.
        /// </summary>
        internal static string EditPrompt {
            get {
                return ResourceManager.GetString("EditPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter category : .
        /// </summary>
        internal static string EnterCategory {
            get {
                return ResourceManager.GetString("EnterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do : .
        /// </summary>
        internal static string EnterChoice {
            get {
                return ResourceManager.GetString("EnterChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the expense  : .
        /// </summary>
        internal static string EnterExpense {
            get {
                return ResourceManager.GetString("EnterExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the income  : .
        /// </summary>
        internal static string EnterIncome {
            get {
                return ResourceManager.GetString("EnterIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the index of transaction to delete: .
        /// </summary>
        internal static string EnterIndexToDelete {
            get {
                return ResourceManager.GetString("EnterIndexToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the index of transaction to edit : .
        /// </summary>
        internal static string EnterIndexToEdit {
            get {
                return ResourceManager.GetString("EnterIndexToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new amount : .
        /// </summary>
        internal static string EnterNewAmount {
            get {
                return ResourceManager.GetString("EnterNewAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new {0} : .
        /// </summary>
        internal static string EnterNewTag {
            get {
                return ResourceManager.GetString("EnterNewTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a source : .
        /// </summary>
        internal static string EnterSource {
            get {
                return ResourceManager.GetString("EnterSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to edit : .
        /// </summary>
        internal static string EnterWhatToEdit {
            get {
                return ResourceManager.GetString("EnterWhatToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Add income\n2. Add expense\n3. View all transactions\n4. Exit application\n.
        /// </summary>
        internal static string MenuPrompt {
            get {
                return ResourceManager.GetString("MenuPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New source.
        /// </summary>
        internal static string NewSource {
            get {
                return ResourceManager.GetString("NewSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0}.
        /// </summary>
        internal static string NewTag {
            get {
                return ResourceManager.GetString("NewTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press enter to go back.....
        /// </summary>
        internal static string PressEnterToGoBack {
            get {
                return ResourceManager.GetString("PressEnterToGoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources : .
        /// </summary>
        internal static string Sources {
            get {
                return ResourceManager.GetString("Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. View incomes \n2. View expenses \n3. Go back.
        /// </summary>
        internal static string ViewPrompt {
            get {
                return ResourceManager.GetString("ViewPrompt", resourceCulture);
            }
        }
    }
}
