//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilesAndStreams.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FilesAndStreams.Constants.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating sample file {0}.
        /// </summary>
        public static string CreatingSampleFile {
            get {
                return ResourceManager.GetString("CreatingSampleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficient file handle.
        /// </summary>
        public static string EfficientFilehandle {
            get {
                return ResourceManager.GetString("EfficientFilehandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time: {0} ms.
        /// </summary>
        public static string Elapsedtime {
            get {
                return ResourceManager.GetString("Elapsedtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulated multiple users logging errors at the same time. Check bin for generated error log files..
        /// </summary>
        public static string ErrorLogFilesSimulated {
            get {
                return ResourceManager.GetString("ErrorLogFilesSimulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File processing started.
        /// </summary>
        public static string FileProcessingStarted {
            get {
                return ResourceManager.GetString("FileProcessingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press enter key to exit task {0} .
        /// </summary>
        public static string PressEnterToExitTask {
            get {
                return ResourceManager.GetString("PressEnterToExitTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading sample files.
        /// </summary>
        public static string ReadingSampleFiles {
            get {
                return ResourceManager.GetString("ReadingSampleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading sample file with {0}.
        /// </summary>
        public static string ReadingSampleFileWith {
            get {
                return ResourceManager.GetString("ReadingSampleFileWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample files creation started.
        /// </summary>
        public static string SampleFileCreationStarted {
            get {
                return ResourceManager.GetString("SampleFileCreationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task {0}.
        /// </summary>
        public static string TaskTitle {
            get {
                return ResourceManager.GetString("TaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing processed data.
        /// </summary>
        public static string WritingProcessedData {
            get {
                return ResourceManager.GetString("WritingProcessedData", resourceCulture);
            }
        }
    }
}
