//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpAdvanced.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharpAdvanced.Constants.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This task demonstrate the the working of anonymous methods\n.
        /// </summary>
        internal static string AnonymousDescription {
            get {
                return ResourceManager.GetString("AnonymousDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nArray after sorting : .
        /// </summary>
        internal static string ArrayAfterSorting {
            get {
                return ResourceManager.GetString("ArrayAfterSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array before sorting : .
        /// </summary>
        internal static string ArrayBeforeSorting {
            get {
                return ResourceManager.GetString("ArrayBeforeSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title : {0} Author : {1} ISBN : {2}.
        /// </summary>
        internal static string BookDetails {
            get {
                return ResourceManager.GetString("BookDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nBooks : .
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This task demonstrate the the working of delegates(Advanced)\n\n.
        /// </summary>
        internal static string DelegatesAdvancedDescription {
            get {
                return ResourceManager.GetString("DelegatesAdvancedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a circle in {0} color with radius : {1}, area : {2:f2}..
        /// </summary>
        internal static string DisplayCircle {
            get {
                return ResourceManager.GetString("DisplayCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nDisplaying the details of book using deconstruction.
        /// </summary>
        internal static string DisplayDetailsUsingDeconstruction {
            get {
                return ResourceManager.GetString("DisplayDetailsUsingDeconstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name : {0}, Category : {1} price {2}.
        /// </summary>
        internal static string DisplayProduct {
            get {
                return ResourceManager.GetString("DisplayProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a rectangle in {0} color with height : {1}, width : {2}, area : {3}..
        /// </summary>
        internal static string DisplayRectangle {
            get {
                return ResourceManager.GetString("DisplayRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following details are about shape objects with different properties, all these shapes types are found with pattern matching.\n.
        /// </summary>
        internal static string DisplayShapes {
            get {
                return ResourceManager.GetString("DisplayShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a triangle in {0} color with base : {1}, height : {2}, area : {3}..
        /// </summary>
        internal static string DisplayTriangle {
            get {
                return ResourceManager.GetString("DisplayTriangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dynamic {0} = {1}, Type : {2}.
        /// </summary>
        internal static string DynamicAndType {
            get {
                return ResourceManager.GetString("DynamicAndType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the message : .
        /// </summary>
        internal static string EnterMessagePrompt {
            get {
                return ResourceManager.GetString("EnterMessagePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter which task to run : .
        /// </summary>
        internal static string EnterTask {
            get {
                return ResourceManager.GetString("EnterTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid option !.
        /// </summary>
        internal static string EnterValidOption {
            get {
                return ResourceManager.GetString("EnterValidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This task demonstrates the working of events and delegates \nWrite any message as a input to trigger the notifier class that displays the info about your message.\n\n.
        /// </summary>
        internal static string EventAndDelegateDescription {
            get {
                return ResourceManager.GetString("EventAndDelegateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input cannot be empty.
        /// </summary>
        internal static string InputCannotBeEmpty {
            get {
                return ResourceManager.GetString("InputCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nIs {0} == {1} : {2}.
        /// </summary>
        internal static string IsEqual {
            get {
                return ResourceManager.GetString("IsEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This task demonstrate the the working of lambda expressions\n\n.
        /// </summary>
        internal static string LambdaExpressionDescription {
            get {
                return ResourceManager.GetString("LambdaExpressionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message : {0}.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of the message : {0}.
        /// </summary>
        internal static string MessageLength {
            get {
                return ResourceManager.GetString("MessageLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message in upper case : {0}.
        /// </summary>
        internal static string MessageUppercase {
            get {
                return ResourceManager.GetString("MessageUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New book : .
        /// </summary>
        internal static string NewBook {
            get {
                return ResourceManager.GetString("NewBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nOriginal book : .
        /// </summary>
        internal static string OriginalBook {
            get {
                return ResourceManager.GetString("OriginalBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This task demonstrate the the working of pattern matching\n\n.
        /// </summary>
        internal static string PatternMatchingDescription {
            get {
                return ResourceManager.GetString("PatternMatchingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This task demonstrate the working of records\n\n.
        /// </summary>
        internal static string RecordsDescription {
            get {
                return ResourceManager.GetString("RecordsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nSorted by category : .
        /// </summary>
        internal static string SortedByCategory {
            get {
                return ResourceManager.GetString("SortedByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted by name : .
        /// </summary>
        internal static string SortedByName {
            get {
                return ResourceManager.GetString("SortedByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nSorted by price : .
        /// </summary>
        internal static string SortedByPrice {
            get {
                return ResourceManager.GetString("SortedByPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nSquared odd numbers : .
        /// </summary>
        internal static string SquaredOddNumbers {
            get {
                return ResourceManager.GetString("SquaredOddNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n\nPress enter to exit task {0}.
        /// </summary>
        internal static string TaskExitPrompt {
            get {
                return ResourceManager.GetString("TaskExitPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggering notifications...
        /// </summary>
        internal static string TriggeringNotifications {
            get {
                return ResourceManager.GetString("TriggeringNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown shape.
        /// </summary>
        internal static string UnknownShape {
            get {
                return ResourceManager.GetString("UnknownShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This task demonstrate the working of var and dynamic keyword\n\n.
        /// </summary>
        internal static string VarAndDynamicDescription {
            get {
                return ResourceManager.GetString("VarAndDynamicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of {0} can&apos;t be changed which will cause a runtime error\n.
        /// </summary>
        internal static string VarAndDynamicMessage1 {
            get {
                return ResourceManager.GetString("VarAndDynamicMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After changing the value of dynamic variable with another type.
        /// </summary>
        internal static string VarAndDynamicMessage2 {
            get {
                return ResourceManager.GetString("VarAndDynamicMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var {0} = {1}, Type : {2}.
        /// </summary>
        internal static string VarAndType {
            get {
                return ResourceManager.GetString("VarAndType", resourceCulture);
            }
        }
    }
}
